# SPDX-FileCopyrightText: Copyright 2022-2026 Jetperch LLC
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - cmake
    - doxygen
    - graphviz
    - libudev-dev
  jobs:
    pre_build:
      - python3 setup.py build_ext --inplace
      - cmake -S . -B cmake-build -DJSDRV_DOCS=1
      - cmake --build cmake-build --target doxygen

# Build documentation in the doc/sphinx/ directory with Sphinx
sphinx:
   configuration: doc/sphinx/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: requirements.txt
   - requirements: doc/requirements.txt
