/*
 * Copyright 2026 Jetperch LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by tools/embed_js320_firmware.py -- do not edit.
// The committed stub carries an empty image; CI overwrites this file
// with the latest stable firmware bytes during the python sdist build.

#include "jsdrv_prv/devices/js320/firmware.h"

const uint8_t js320_firmware[1] = {0};
