#!/usr/bin/env python3
# Copyright 2026 Jetperch LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Embed the latest stable JS320 firmware image into the driver.

Fetches index.json from download.joulescope.com, downloads the stable
image, verifies size and SHA-256, and regenerates:
    include_private/jsdrv_prv/devices/js320/firmware.h
    src/devices/js320/firmware.c

Run from the repository root, before `python -m build --sdist`:
    python tools/embed_js320_firmware.py
    python tools/embed_js320_firmware.py --dry-run   # verify without writing

For development boards whose keys don't match the official release, embed
a locally-built zip instead:
    python tools/embed_js320_firmware.py --zip path/to/js320_p1_mfg.zip \\
        --version 0.4.3
When --zip is given, --index-url is ignored and no network access happens.
"""

import argparse
import hashlib
import json
import os
import re
import sys
import urllib.request


_DEFAULT_INDEX_URL = 'https://download.joulescope.com/firmware/js320/index.json'
_DEFAULT_H_PATH = 'include_private/jsdrv_prv/devices/js320/firmware.h'
_DEFAULT_C_PATH = 'src/devices/js320/firmware.c'

_LICENSE_HEADER = """\
/*
 * Copyright 2026 Jetperch LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by tools/embed_js320_firmware.py -- do not edit.
"""


def fetch_url(url, timeout=60):
    with urllib.request.urlopen(url, timeout=timeout) as resp:
        return resp.read()


def fetch_index(index_url, timeout=60):
    return json.loads(fetch_url(index_url, timeout).decode('utf-8'))


def fetch_image(index_url, entry, timeout=120):
    base = index_url.rsplit('/', 1)[0]
    image_url = f"{base}/{entry['path']}"
    data = fetch_url(image_url, timeout)
    if len(data) != entry['size']:
        raise RuntimeError(
            f'size mismatch for {image_url}: '
            f'index says {entry["size"]}, got {len(data)}')
    digest = hashlib.sha256(data).hexdigest()
    if digest != entry['sha256']:
        raise RuntimeError(
            f'sha256 mismatch for {image_url}: '
            f'index says {entry["sha256"]}, got {digest}')
    return data, image_url


def generate_header(version, size):
    major, minor, patch = version
    return f"""{_LICENSE_HEADER}
#ifndef JSDRV_DEVICES_JS320_FIRMWARE_H_
#define JSDRV_DEVICES_JS320_FIRMWARE_H_

#include <stdint.h>

#define JS320_FIRMWARE_VERSION_MAJOR {major}
#define JS320_FIRMWARE_VERSION_MINOR {minor}
#define JS320_FIRMWARE_VERSION_PATCH {patch}
#define JS320_FIRMWARE_SIZE          {size}

extern const uint8_t js320_firmware[];

#endif  // JSDRV_DEVICES_JS320_FIRMWARE_H_
"""


def generate_source(data):
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append('    ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',')
    body = '\n'.join(lines)
    return f"""{_LICENSE_HEADER}
#include "jsdrv_prv/devices/js320/firmware.h"

const uint8_t js320_firmware[JS320_FIRMWARE_SIZE] = {{
{body}
}};
"""


_VERSION_RE = re.compile(r'^(\d+)\.(\d+)\.(\d+)$')


def parse_version(s):
    m = _VERSION_RE.match(s.strip())
    if not m:
        raise ValueError(f'expected major.minor.patch, got {s!r}')
    return tuple(int(p) for p in m.groups())


def load_local_zip(path, version_str):
    if not os.path.isfile(path):
        raise RuntimeError(f'zip not found: {path}')
    with open(path, 'rb') as f:
        data = f.read()
    if not version_str:
        # Unknown version when using a local zip — emit zeros and warn.
        # Nothing in the driver currently reads these macros, but picking
        # a deliberate sentinel makes it obvious in a header diff that
        # this build came from a dev image, not a release.
        print('WARNING: --version not provided with --zip; using 0.0.0. '
              'Pass --version X.Y.Z to stamp a real version.')
        version = (0, 0, 0)
    else:
        version = parse_version(version_str)
    return data, version


def write_if_changed(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    # Compare before writing so unchanged regens don't touch mtimes and
    # surprise incremental build systems.
    if os.path.isfile(path):
        with open(path, 'r', encoding='utf-8', newline='\n') as f:
            if f.read() == content:
                return False
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(content)
    return True


def main():
    parser = argparse.ArgumentParser(
        description='Embed the latest stable JS320 firmware image.')
    parser.add_argument('--index-url', default=_DEFAULT_INDEX_URL,
                        help=f'index.json URL (default: {_DEFAULT_INDEX_URL})')
    parser.add_argument('--zip',
                        help='Path to a local fwup zip to embed instead of '
                             'fetching from --index-url. Use for dev-signed '
                             'builds whose keys differ from production.')
    parser.add_argument('--version',
                        help='Version "M.m.p" to stamp into firmware.h when '
                             'using --zip. Defaults to 0.0.0 with a warning.')
    parser.add_argument('--output-h', default=_DEFAULT_H_PATH,
                        help=f'header output path (default: {_DEFAULT_H_PATH})')
    parser.add_argument('--output-c', default=_DEFAULT_C_PATH,
                        help=f'source output path (default: {_DEFAULT_C_PATH})')
    parser.add_argument('--dry-run', action='store_true',
                        help='Fetch and verify, but do not write files')
    args = parser.parse_args()

    if args.zip:
        data, version = load_local_zip(args.zip, args.version)
        print(f'source:   {args.zip} (local, skipping network fetch)')
        print(f'version:  {".".join(str(v) for v in version)}')
        print(f'size:     {len(data)} bytes')
        print(f'sha256:   {hashlib.sha256(data).hexdigest()}')
    else:
        if args.version:
            raise SystemExit('--version is only meaningful with --zip; '
                             'without --zip the version comes from index.json')
        index = fetch_index(args.index_url)
        try:
            entry = index[0]
        except KeyError:
            raise RuntimeError(
                f'no js320.stable entry in {args.index_url}')

        data, image_url = fetch_image(args.index_url, entry)
        version = tuple(entry['version'])

        print(f'index:    {args.index_url}')
        print(f'image:    {image_url}')
        print(f'version:  {".".join(str(v) for v in version)}')
        print(f'size:     {len(data)} bytes')
        print(f'sha256:   {entry["sha256"]}')

    h_content = generate_header(version, len(data))
    c_content = generate_source(data)

    if args.dry_run:
        print(f'[dry-run] would write {args.output_h} ({len(h_content)} bytes)')
        print(f'[dry-run] would write {args.output_c} ({len(c_content)} bytes)')
        return 0

    changed_h = write_if_changed(args.output_h, h_content)
    changed_c = write_if_changed(args.output_c, c_content)
    print(f'{"wrote" if changed_h else "unchanged"}: {args.output_h}')
    print(f'{"wrote" if changed_c else "unchanged"}: {args.output_c}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
